// GET /terms — the deal between us and a keeper.
//
// Deliberately short, and deliberately blunt about the AI: identification
// and care guides are generated, and the toxicity field in a care guide is
// the one place where trusting a wrong answer could hurt somebody.
import { CONTACT, ENTITY, ENTITY_FULL, legalPage, serve, UPDATED } from "./legal";

const sections = [
  {
    heading: "What this is",
    html: `<p>PlantParlour is a place to keep the record of your plants — what they are, what you have done for them, and the story you would want to pass on with a cutting. It is free to use, and it is a small operation: there is no support desk, just us.</p>
<p>PlantParlour is operated by <strong>${ENTITY_FULL}</strong> ("we", "us", "our"). These terms are a binding agreement between you and ${ENTITY}. By making an account or using the service, you accept them. If you do not, please do not use it.</p>`,
  },
  {
    heading: "Your account",
    html: `<ul>
<li>You need to be 13 or older, and old enough to enter a contract where you live.</li>
<li>Give us an email address that reaches you, and keep your password to yourself. Everything done under your account is your responsibility.</li>
<li>One account per person. If you lose access to your email, we may not be able to get you back in.</li>
<li>Tell us promptly if you think someone else is using your account.</li>
</ul>
<p>We may suspend or close an account that breaks these terms, and we may stop offering the service to anyone, at our discretion.</p>`,
  },
  {
    heading: "Your plants stay yours",
    html: `<p>Everything you put into PlantParlour — your notes, your photos, your records — remains yours. You are not signing it over to us.</p>
<p>You give us a non-exclusive, worldwide, royalty-free licence to store, copy and display it, for as long as you keep it here and only so far as running the service requires: showing it back to you, and showing it publicly <em>only</em> where you have chosen to publish — a tag link you created, or your conservatory page. Unpublish it and that part of the licence ends with it. Delete your account and the licence ends entirely, apart from backups that age out on their own.</p>
<p>You promise that what you upload is yours to upload, and that showing it here breaks nobody's rights. You agree to cover us for any claim, loss or legal cost that comes out of what you uploaded or how you used PlantParlour.</p>`,
  },
  {
    heading: "What not to do",
    html: `<ul>
<li>Do not upload photos or writing that are not yours to share.</li>
<li>Do not use PlantParlour for anything unlawful, or to harass anybody.</li>
<li>Do not scrape it, hammer it, reverse-engineer it, or try to reach another keeper's records.</li>
<li>Do not use it to sell plants whose sale or import is restricted where you are. A tag is a record, not a permit.</li>
</ul>
<p>If an account is doing one of these, we may suspend or remove it without notice.</p>`,
  },
  {
    heading: "The AI can be wrong",
    html: `<p>Plant identification and care guides are generated by an AI model. Most of the time it is good. It is not always right, and it is confidently wrong sometimes — particularly on cultivars, and on plants that look like other plants.</p>
<p><strong>Treat every AI answer as a well-informed guess, not a fact.</strong> It is information, not professional, horticultural, veterinary or medical advice. Check anything that matters against a second source before you act on it.</p>
<p><strong>This goes double for toxicity.</strong> Never rely on a care guide to decide whether a plant is safe around a child, a cat, a dog, or safe to eat. If someone has eaten part of a plant, call a doctor, a vet, or your local poison control line — not this app.</p>`,
  },
  {
    heading: "Sold as seen",
    html: `<p class="legal"><strong>PlantParlour is provided "as is" and "as available", without warranty of any kind.</strong> To the fullest extent the law allows, we disclaim all warranties, express or implied, including any implied warranty of merchantability, fitness for a particular purpose, title and non-infringement, and any warranty arising from how the service has been used or performed before.</p>
<p class="legal">We do not warrant that PlantParlour will be uninterrupted, timely, secure or error-free, that any defect will be fixed, or that anything it tells you — an identification, a care guide, a reminder — is accurate, complete or reliable.</p>
<p>Some states do not allow certain warranties to be disclaimed, so some of the above may not apply to you.</p>`,
  },
  {
    heading: "What we are liable for",
    html: `<p class="legal"><strong>To the fullest extent the law allows, we are not liable for any indirect, incidental, special, consequential, exemplary or punitive damages</strong>, nor for lost profits, lost data, lost plants, lost goodwill, or the cost of anything bought to replace the service — whether the claim is in contract, tort, negligence, strict liability or anything else, and even if we were told such damage was possible.</p>
<p class="legal"><strong>The total liability of ${ENTITY}, and of its members, managers and employees, to you for everything arising out of these terms or your use of PlantParlour will not exceed one hundred US dollars ($100).</strong> PlantParlour is free, so there are no fees to refund, and this cap is part of what makes offering it free possible.</p>
<p>Nothing here limits liability that cannot be limited by law — including fraud, or death or personal injury caused by negligence. Some states do not allow these exclusions, so some of them may not apply to you.</p>
<p><strong>Any claim must be brought within one year</strong> of when it arose, or it is permanently barred, unless the law where you live forbids shortening that period.</p>`,
  },
  {
    heading: "If we stop",
    html: `<p>We may change how PlantParlour works, or stop running it. If we ever shut it down, we will give you notice and a way to take your records with you before anything is deleted. We will not quietly disappear with your plant history.</p>
<p>We are not responsible for a delay or failure caused by something outside our reasonable control — an outage at a provider we depend on, a network failure, a natural disaster.</p>`,
  },
  {
    heading: "Colorado law, and settling disagreements",
    html: `<p>These terms, and any dispute arising out of them or out of your use of PlantParlour, are governed by the laws of the State of Colorado, without regard to its conflict-of-laws rules. The Federal Arbitration Act governs the arbitration agreement below.</p>
<p><strong>Talk to us first.</strong> Almost everything is fixable by email. Before starting anything formal, send a description of the problem and what you want to <a href="mailto:${CONTACT}">${CONTACT}</a> and give us 30 days to put it right. This step is a condition of starting arbitration.</p>
<p class="legal"><strong>Arbitration, not court.</strong> If that does not resolve it, you and we agree that the dispute will be resolved by <strong>binding individual arbitration</strong> before a single arbitrator, administered by the American Arbitration Association under its Consumer Arbitration Rules, and <strong>not in court before a judge or jury. You and we are giving up the right to sue in court and the right to a jury trial.</strong> It can be heard in Colorado, remotely, or in the county where you live — your choice. Judgment on the award may be entered in any court with jurisdiction.</p>
<p class="legal"><strong>Individually, not as a class.</strong> Claims must be brought in your own name, not as a plaintiff or class member in any class, collective, consolidated or representative action, and the arbitrator may not consolidate more than one person's claims or preside over any representative proceeding. If this paragraph is found unenforceable, the whole of this arbitration section does not apply and the dispute goes to court. A court, not the arbitrator, decides whether this paragraph is enforceable.</p>
<p><strong>The arbitrator decides the rest.</strong> Apart from that one paragraph, questions about whether this agreement to arbitrate applies, covers a particular dispute, or is enforceable are for the arbitrator, not a court.</p>
<p><strong>Who pays.</strong> Fees are allocated by the AAA Consumer Arbitration Rules and the AAA fee schedule in force at the time, which cap what a consumer pays and put the rest on the business. If the arbitrator finds a claim was frivolous or brought for an improper purpose, they may shift fees as those rules allow. We make no commitment beyond what those rules require.</p>
<p><strong>Small claims court is still open.</strong> Either of us may bring a qualifying claim in small claims court instead of arbitration. Either of us may also ask a court for an injunction to stop misuse of our intellectual property, without waiting for arbitration.</p>
<p><strong>You can opt out, and it costs you nothing.</strong> Email <a href="mailto:${CONTACT}">${CONTACT}</a> with the subject line <em>Arbitration opt-out</em>, and your name and the email on your account, within 30 days of first agreeing to these terms, and this arbitration section will not apply to you. If you already had an account before ${UPDATED}, your 30 days run from that date. Opting out changes nothing else about your account, and we will not hold it against you.</p>
<p>Where a dispute is not subject to arbitration, you and we agree to the exclusive jurisdiction of the state and federal courts located in Colorado, and to venue there.</p>`,
  },
  {
    heading: "Leaving",
    html: `<p>You can stop using PlantParlour at any time. To have your account and everything in it erased, email <a href="mailto:${CONTACT}">${CONTACT}</a> from the address you signed up with — see the <a href="/privacy">privacy page</a> for what that covers and how long it takes.</p>`,
  },
  {
    heading: "Odds and ends",
    html: `<ul>
<li><strong>Severability.</strong> If any part of these terms is unenforceable, it is limited or removed to the smallest extent needed and the rest still stands.</li>
<li><strong>No waiver.</strong> If we do not enforce something straight away, we have not given up the right to enforce it later.</li>
<li><strong>Survival.</strong> The sections on your content licence, the AI, warranties, liability, disputes and these odds and ends survive your account ending.</li>
<li><strong>Entire agreement.</strong> These terms and the <a href="/privacy">privacy page</a> are the whole agreement between us about PlantParlour, and replace anything said before.</li>
<li><strong>Assignment.</strong> Your account cannot be transferred. ${ENTITY} may transfer these terms if PlantParlour changes hands, and we will tell you before it does.</li>
<li><strong>Notices.</strong> We reach you at the email on your account; you reach us at <a href="mailto:${CONTACT}">${CONTACT}</a>. You agree to receive communications about the service electronically.</li>
</ul>`,
  },
  {
    heading: "Changes",
    html: `<p>If these terms change, we will update this page and the date at the top, and say so in the app if the change is significant. Carrying on using PlantParlour after a change means the new version applies. A change to the arbitration section does not apply to a dispute we already knew about.</p>`,
  },
];

export default function handler(req: Parameters<typeof serve>[0], res: Parameters<typeof serve>[1]): void {
  serve(req, res, () =>
    legalPage(
      "Terms",
      "The short version: your plants are yours, we will look after them, the AI is a helpful guess rather than an expert, and you can leave with your records whenever you like. These terms are governed by Colorado law and include a <strong>binding arbitration agreement, a jury-trial waiver and a class-action waiver</strong> — you give up the right to sue in court — which you may opt out of within 30 days. They also limit our liability.",
      sections,
      "The terms of using PlantParlour: your content, what the AI can and cannot be trusted with, and how to leave.",
    ),
  );
}
